/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_IDENTIFIERS_SPOTIFY_LOGIN5_V3_IDENTIFIERS_IDENTIFIERS_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_IDENTIFIERS_SPOTIFY_LOGIN5_V3_IDENTIFIERS_IDENTIFIERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _spotify_login5_v3_identifiers_PhoneNumber {
    pb_callback_t number;
    pb_callback_t iso_country_code;
    pb_callback_t country_calling_code;
} spotify_login5_v3_identifiers_PhoneNumber;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define spotify_login5_v3_identifiers_PhoneNumber_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_identifiers_PhoneNumber_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_identifiers_PhoneNumber_number_tag 1
#define spotify_login5_v3_identifiers_PhoneNumber_iso_country_code_tag 2
#define spotify_login5_v3_identifiers_PhoneNumber_country_calling_code_tag 3

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_identifiers_PhoneNumber_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   number,            1) \
X(a, CALLBACK, SINGULAR, STRING,   iso_country_code,   2) \
X(a, CALLBACK, SINGULAR, STRING,   country_calling_code,   3)
#define spotify_login5_v3_identifiers_PhoneNumber_CALLBACK pb_default_field_callback
#define spotify_login5_v3_identifiers_PhoneNumber_DEFAULT NULL

extern const pb_msgdesc_t spotify_login5_v3_identifiers_PhoneNumber_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_identifiers_PhoneNumber_fields &spotify_login5_v3_identifiers_PhoneNumber_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_identifiers_PhoneNumber_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
