/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_CLIENT_INFO_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_CLIENT_INFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _spotify_login5_v3_ClientInfo {
    pb_callback_t client_id;
    pb_callback_t device_id;
} spotify_login5_v3_ClientInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define spotify_login5_v3_ClientInfo_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_ClientInfo_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_ClientInfo_client_id_tag 1
#define spotify_login5_v3_ClientInfo_device_id_tag 2

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_ClientInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   client_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         2)
#define spotify_login5_v3_ClientInfo_CALLBACK pb_default_field_callback
#define spotify_login5_v3_ClientInfo_DEFAULT NULL

extern const pb_msgdesc_t spotify_login5_v3_ClientInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_ClientInfo_fields &spotify_login5_v3_ClientInfo_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_ClientInfo_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
