/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "spotify/login5/v3/login5.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(spotify_login5_v3_Challenges, spotify_login5_v3_Challenges, AUTO)


PB_BIND(spotify_login5_v3_Challenge, spotify_login5_v3_Challenge, AUTO)


PB_BIND(spotify_login5_v3_ChallengeSolutions, spotify_login5_v3_ChallengeSolutions, AUTO)


PB_BIND(spotify_login5_v3_ChallengeSolution, spotify_login5_v3_ChallengeSolution, AUTO)


PB_BIND(spotify_login5_v3_LoginRequest, spotify_login5_v3_LoginRequest, 2)


PB_BIND(spotify_login5_v3_LoginOk, spotify_login5_v3_LoginOk, AUTO)


PB_BIND(spotify_login5_v3_LoginResponse, spotify_login5_v3_LoginResponse, AUTO)







