/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_LOGIN5_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_LOGIN5_PB_H_INCLUDED
#include <pb.h>
#include "spotify/login5/v3/client_info.pb.h"
#include "spotify/login5/v3/user_info.pb.h"
#include "spotify/login5/v3/challenges/code.pb.h"
#include "spotify/login5/v3/challenges/hashcash.pb.h"
#include "spotify/login5/v3/credentials/credentials.pb.h"
#include "spotify/login5/v3/identifiers/identifiers.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _spotify_login5_v3_LoginError {
    spotify_login5_v3_LoginError_UNKNOWN_ERROR = 0,
    spotify_login5_v3_LoginError_INVALID_CREDENTIALS = 1,
    spotify_login5_v3_LoginError_BAD_REQUEST = 2,
    spotify_login5_v3_LoginError_UNSUPPORTED_LOGIN_PROTOCOL = 3,
    spotify_login5_v3_LoginError_TIMEOUT = 4,
    spotify_login5_v3_LoginError_UNKNOWN_IDENTIFIER = 5,
    spotify_login5_v3_LoginError_TOO_MANY_ATTEMPTS = 6,
    spotify_login5_v3_LoginError_INVALID_PHONENUMBER = 7,
    spotify_login5_v3_LoginError_TRY_AGAIN_LATER = 8
} spotify_login5_v3_LoginError;

typedef enum _spotify_login5_v3_LoginResponse_Warnings {
    spotify_login5_v3_LoginResponse_Warnings_UNKNOWN_WARNING = 0,
    spotify_login5_v3_LoginResponse_Warnings_DEPRECATED_PROTOCOL_VERSION = 1
} spotify_login5_v3_LoginResponse_Warnings;

/* Struct definitions */
typedef struct _spotify_login5_v3_Challenges {
    pb_callback_t challenges;
} spotify_login5_v3_Challenges;

typedef struct _spotify_login5_v3_Challenge {
    pb_size_t which_challenge;
    union _spotify_login5_v3_Challenge_challenge {
        spotify_login5_v3_challenges_HashcashChallenge hashcash;
        spotify_login5_v3_challenges_CodeChallenge code;
    } challenge;
} spotify_login5_v3_Challenge;

typedef struct _spotify_login5_v3_ChallengeSolutions {
    pb_callback_t solutions;
} spotify_login5_v3_ChallengeSolutions;

typedef struct _spotify_login5_v3_ChallengeSolution {
    pb_size_t which_solution;
    union _spotify_login5_v3_ChallengeSolution_solution {
        spotify_login5_v3_challenges_HashcashSolution hashcash;
        spotify_login5_v3_challenges_CodeSolution code;
    } solution;
} spotify_login5_v3_ChallengeSolution;

typedef struct _spotify_login5_v3_LoginRequest {
    bool has_client_info;
    spotify_login5_v3_ClientInfo client_info;
    pb_callback_t login_context;
    bool has_challenge_solutions;
    spotify_login5_v3_ChallengeSolutions challenge_solutions;
    pb_size_t which_login_method;
    union _spotify_login5_v3_LoginRequest_login_method {
        spotify_login5_v3_credentials_StoredCredential stored_credential;
        spotify_login5_v3_credentials_Password password;
        spotify_login5_v3_credentials_FacebookAccessToken facebook_access_token;
        spotify_login5_v3_identifiers_PhoneNumber phone_number;
        spotify_login5_v3_credentials_OneTimeToken one_time_token;
        spotify_login5_v3_credentials_ParentChildCredential parent_child_credential;
        spotify_login5_v3_credentials_AppleSignInCredential apple_sign_in_credential;
        spotify_login5_v3_credentials_SamsungSignInCredential samsung_sign_in_credential;
        spotify_login5_v3_credentials_GoogleSignInCredential google_sign_in_credential;
    } login_method;
} spotify_login5_v3_LoginRequest;

typedef struct _spotify_login5_v3_LoginOk {
    pb_callback_t username;
    pb_callback_t access_token;
    pb_callback_t stored_credential;
    int32_t access_token_expires_in;
} spotify_login5_v3_LoginOk;

typedef struct _spotify_login5_v3_LoginResponse {
    pb_size_t which_response;
    union _spotify_login5_v3_LoginResponse_response {
        spotify_login5_v3_LoginOk ok;
        spotify_login5_v3_LoginError error;
        spotify_login5_v3_Challenges challenges;
    } response;
    pb_callback_t warnings;
    pb_callback_t login_context;
    pb_callback_t identifier_token;
    bool has_user_info;
    spotify_login5_v3_UserInfo user_info;
} spotify_login5_v3_LoginResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _spotify_login5_v3_LoginError_MIN spotify_login5_v3_LoginError_UNKNOWN_ERROR
#define _spotify_login5_v3_LoginError_MAX spotify_login5_v3_LoginError_TRY_AGAIN_LATER
#define _spotify_login5_v3_LoginError_ARRAYSIZE ((spotify_login5_v3_LoginError)(spotify_login5_v3_LoginError_TRY_AGAIN_LATER+1))

#define _spotify_login5_v3_LoginResponse_Warnings_MIN spotify_login5_v3_LoginResponse_Warnings_UNKNOWN_WARNING
#define _spotify_login5_v3_LoginResponse_Warnings_MAX spotify_login5_v3_LoginResponse_Warnings_DEPRECATED_PROTOCOL_VERSION
#define _spotify_login5_v3_LoginResponse_Warnings_ARRAYSIZE ((spotify_login5_v3_LoginResponse_Warnings)(spotify_login5_v3_LoginResponse_Warnings_DEPRECATED_PROTOCOL_VERSION+1))







#define spotify_login5_v3_LoginResponse_response_error_ENUMTYPE spotify_login5_v3_LoginError
#define spotify_login5_v3_LoginResponse_warnings_ENUMTYPE spotify_login5_v3_LoginResponse_Warnings


/* Initializer values for message structs */
#define spotify_login5_v3_Challenges_init_default {{{NULL}, NULL}}
#define spotify_login5_v3_Challenge_init_default {0, {spotify_login5_v3_challenges_HashcashChallenge_init_default}}
#define spotify_login5_v3_ChallengeSolutions_init_default {{{NULL}, NULL}}
#define spotify_login5_v3_ChallengeSolution_init_default {0, {spotify_login5_v3_challenges_HashcashSolution_init_default}}
#define spotify_login5_v3_LoginRequest_init_default {false, spotify_login5_v3_ClientInfo_init_default, {{NULL}, NULL}, false, spotify_login5_v3_ChallengeSolutions_init_default, 0, {spotify_login5_v3_credentials_StoredCredential_init_default}}
#define spotify_login5_v3_LoginOk_init_default   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define spotify_login5_v3_LoginResponse_init_default {0, {spotify_login5_v3_LoginOk_init_default}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, spotify_login5_v3_UserInfo_init_default}
#define spotify_login5_v3_Challenges_init_zero   {{{NULL}, NULL}}
#define spotify_login5_v3_Challenge_init_zero    {0, {spotify_login5_v3_challenges_HashcashChallenge_init_zero}}
#define spotify_login5_v3_ChallengeSolutions_init_zero {{{NULL}, NULL}}
#define spotify_login5_v3_ChallengeSolution_init_zero {0, {spotify_login5_v3_challenges_HashcashSolution_init_zero}}
#define spotify_login5_v3_LoginRequest_init_zero {false, spotify_login5_v3_ClientInfo_init_zero, {{NULL}, NULL}, false, spotify_login5_v3_ChallengeSolutions_init_zero, 0, {spotify_login5_v3_credentials_StoredCredential_init_zero}}
#define spotify_login5_v3_LoginOk_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define spotify_login5_v3_LoginResponse_init_zero {0, {spotify_login5_v3_LoginOk_init_zero}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, spotify_login5_v3_UserInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_Challenges_challenges_tag 1
#define spotify_login5_v3_Challenge_hashcash_tag 1
#define spotify_login5_v3_Challenge_code_tag     2
#define spotify_login5_v3_ChallengeSolutions_solutions_tag 1
#define spotify_login5_v3_ChallengeSolution_hashcash_tag 1
#define spotify_login5_v3_ChallengeSolution_code_tag 2
#define spotify_login5_v3_LoginRequest_client_info_tag 1
#define spotify_login5_v3_LoginRequest_login_context_tag 2
#define spotify_login5_v3_LoginRequest_challenge_solutions_tag 3
#define spotify_login5_v3_LoginRequest_stored_credential_tag 100
#define spotify_login5_v3_LoginRequest_password_tag 101
#define spotify_login5_v3_LoginRequest_facebook_access_token_tag 102
#define spotify_login5_v3_LoginRequest_phone_number_tag 103
#define spotify_login5_v3_LoginRequest_one_time_token_tag 104
#define spotify_login5_v3_LoginRequest_parent_child_credential_tag 105
#define spotify_login5_v3_LoginRequest_apple_sign_in_credential_tag 106
#define spotify_login5_v3_LoginRequest_samsung_sign_in_credential_tag 107
#define spotify_login5_v3_LoginRequest_google_sign_in_credential_tag 108
#define spotify_login5_v3_LoginOk_username_tag   1
#define spotify_login5_v3_LoginOk_access_token_tag 2
#define spotify_login5_v3_LoginOk_stored_credential_tag 3
#define spotify_login5_v3_LoginOk_access_token_expires_in_tag 4
#define spotify_login5_v3_LoginResponse_ok_tag   1
#define spotify_login5_v3_LoginResponse_error_tag 2
#define spotify_login5_v3_LoginResponse_challenges_tag 3
#define spotify_login5_v3_LoginResponse_warnings_tag 4
#define spotify_login5_v3_LoginResponse_login_context_tag 5
#define spotify_login5_v3_LoginResponse_identifier_token_tag 6
#define spotify_login5_v3_LoginResponse_user_info_tag 7

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_Challenges_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  challenges,        1)
#define spotify_login5_v3_Challenges_CALLBACK pb_default_field_callback
#define spotify_login5_v3_Challenges_DEFAULT NULL
#define spotify_login5_v3_Challenges_challenges_MSGTYPE spotify_login5_v3_Challenge

#define spotify_login5_v3_Challenge_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (challenge,hashcash,challenge.hashcash),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (challenge,code,challenge.code),   2)
#define spotify_login5_v3_Challenge_CALLBACK NULL
#define spotify_login5_v3_Challenge_DEFAULT NULL
#define spotify_login5_v3_Challenge_challenge_hashcash_MSGTYPE spotify_login5_v3_challenges_HashcashChallenge
#define spotify_login5_v3_Challenge_challenge_code_MSGTYPE spotify_login5_v3_challenges_CodeChallenge

#define spotify_login5_v3_ChallengeSolutions_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  solutions,         1)
#define spotify_login5_v3_ChallengeSolutions_CALLBACK pb_default_field_callback
#define spotify_login5_v3_ChallengeSolutions_DEFAULT NULL
#define spotify_login5_v3_ChallengeSolutions_solutions_MSGTYPE spotify_login5_v3_ChallengeSolution

#define spotify_login5_v3_ChallengeSolution_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (solution,hashcash,solution.hashcash),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (solution,code,solution.code),   2)
#define spotify_login5_v3_ChallengeSolution_CALLBACK NULL
#define spotify_login5_v3_ChallengeSolution_DEFAULT NULL
#define spotify_login5_v3_ChallengeSolution_solution_hashcash_MSGTYPE spotify_login5_v3_challenges_HashcashSolution
#define spotify_login5_v3_ChallengeSolution_solution_code_MSGTYPE spotify_login5_v3_challenges_CodeSolution

#define spotify_login5_v3_LoginRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  client_info,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    login_context,     2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  challenge_solutions,   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,stored_credential,login_method.stored_credential), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,password,login_method.password), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,facebook_access_token,login_method.facebook_access_token), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,phone_number,login_method.phone_number), 103) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,one_time_token,login_method.one_time_token), 104) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,parent_child_credential,login_method.parent_child_credential), 105) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,apple_sign_in_credential,login_method.apple_sign_in_credential), 106) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,samsung_sign_in_credential,login_method.samsung_sign_in_credential), 107) \
X(a, STATIC,   ONEOF,    MESSAGE,  (login_method,google_sign_in_credential,login_method.google_sign_in_credential), 108)
#define spotify_login5_v3_LoginRequest_CALLBACK pb_default_field_callback
#define spotify_login5_v3_LoginRequest_DEFAULT NULL
#define spotify_login5_v3_LoginRequest_client_info_MSGTYPE spotify_login5_v3_ClientInfo
#define spotify_login5_v3_LoginRequest_challenge_solutions_MSGTYPE spotify_login5_v3_ChallengeSolutions
#define spotify_login5_v3_LoginRequest_login_method_stored_credential_MSGTYPE spotify_login5_v3_credentials_StoredCredential
#define spotify_login5_v3_LoginRequest_login_method_password_MSGTYPE spotify_login5_v3_credentials_Password
#define spotify_login5_v3_LoginRequest_login_method_facebook_access_token_MSGTYPE spotify_login5_v3_credentials_FacebookAccessToken
#define spotify_login5_v3_LoginRequest_login_method_phone_number_MSGTYPE spotify_login5_v3_identifiers_PhoneNumber
#define spotify_login5_v3_LoginRequest_login_method_one_time_token_MSGTYPE spotify_login5_v3_credentials_OneTimeToken
#define spotify_login5_v3_LoginRequest_login_method_parent_child_credential_MSGTYPE spotify_login5_v3_credentials_ParentChildCredential
#define spotify_login5_v3_LoginRequest_login_method_apple_sign_in_credential_MSGTYPE spotify_login5_v3_credentials_AppleSignInCredential
#define spotify_login5_v3_LoginRequest_login_method_samsung_sign_in_credential_MSGTYPE spotify_login5_v3_credentials_SamsungSignInCredential
#define spotify_login5_v3_LoginRequest_login_method_google_sign_in_credential_MSGTYPE spotify_login5_v3_credentials_GoogleSignInCredential

#define spotify_login5_v3_LoginOk_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   username,          1) \
X(a, CALLBACK, SINGULAR, STRING,   access_token,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    stored_credential,   3) \
X(a, STATIC,   SINGULAR, INT32,    access_token_expires_in,   4)
#define spotify_login5_v3_LoginOk_CALLBACK pb_default_field_callback
#define spotify_login5_v3_LoginOk_DEFAULT NULL

#define spotify_login5_v3_LoginResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ok,response.ok),   1) \
X(a, STATIC,   ONEOF,    UENUM,    (response,error,response.error),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,challenges,response.challenges),   3) \
X(a, CALLBACK, REPEATED, UENUM,    warnings,          4) \
X(a, CALLBACK, SINGULAR, BYTES,    login_context,     5) \
X(a, CALLBACK, SINGULAR, STRING,   identifier_token,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user_info,         7)
#define spotify_login5_v3_LoginResponse_CALLBACK pb_default_field_callback
#define spotify_login5_v3_LoginResponse_DEFAULT NULL
#define spotify_login5_v3_LoginResponse_response_ok_MSGTYPE spotify_login5_v3_LoginOk
#define spotify_login5_v3_LoginResponse_response_challenges_MSGTYPE spotify_login5_v3_Challenges
#define spotify_login5_v3_LoginResponse_user_info_MSGTYPE spotify_login5_v3_UserInfo

extern const pb_msgdesc_t spotify_login5_v3_Challenges_msg;
extern const pb_msgdesc_t spotify_login5_v3_Challenge_msg;
extern const pb_msgdesc_t spotify_login5_v3_ChallengeSolutions_msg;
extern const pb_msgdesc_t spotify_login5_v3_ChallengeSolution_msg;
extern const pb_msgdesc_t spotify_login5_v3_LoginRequest_msg;
extern const pb_msgdesc_t spotify_login5_v3_LoginOk_msg;
extern const pb_msgdesc_t spotify_login5_v3_LoginResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_Challenges_fields &spotify_login5_v3_Challenges_msg
#define spotify_login5_v3_Challenge_fields &spotify_login5_v3_Challenge_msg
#define spotify_login5_v3_ChallengeSolutions_fields &spotify_login5_v3_ChallengeSolutions_msg
#define spotify_login5_v3_ChallengeSolution_fields &spotify_login5_v3_ChallengeSolution_msg
#define spotify_login5_v3_LoginRequest_fields &spotify_login5_v3_LoginRequest_msg
#define spotify_login5_v3_LoginOk_fields &spotify_login5_v3_LoginOk_msg
#define spotify_login5_v3_LoginResponse_fields &spotify_login5_v3_LoginResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(spotify_login5_v3_challenges_HashcashChallenge_size) && defined(spotify_login5_v3_challenges_CodeChallenge_size)
union spotify_login5_v3_Challenge_challenge_size_union {char f1[(6 + spotify_login5_v3_challenges_HashcashChallenge_size)]; char f2[(6 + spotify_login5_v3_challenges_CodeChallenge_size)];};
#endif
#if defined(spotify_login5_v3_challenges_HashcashSolution_size) && defined(spotify_login5_v3_challenges_CodeSolution_size)
union spotify_login5_v3_ChallengeSolution_solution_size_union {char f1[(6 + spotify_login5_v3_challenges_HashcashSolution_size)]; char f2[(6 + spotify_login5_v3_challenges_CodeSolution_size)];};
#endif
#if defined(spotify_login5_v3_credentials_StoredCredential_size) && defined(spotify_login5_v3_credentials_Password_size) && defined(spotify_login5_v3_credentials_FacebookAccessToken_size) && defined(spotify_login5_v3_identifiers_PhoneNumber_size) && defined(spotify_login5_v3_credentials_OneTimeToken_size) && defined(spotify_login5_v3_credentials_ParentChildCredential_size) && defined(spotify_login5_v3_credentials_AppleSignInCredential_size) && defined(spotify_login5_v3_credentials_SamsungSignInCredential_size) && defined(spotify_login5_v3_credentials_GoogleSignInCredential_size)
union spotify_login5_v3_LoginRequest_login_method_size_union {char f100[(7 + spotify_login5_v3_credentials_StoredCredential_size)]; char f101[(7 + spotify_login5_v3_credentials_Password_size)]; char f102[(7 + spotify_login5_v3_credentials_FacebookAccessToken_size)]; char f103[(7 + spotify_login5_v3_identifiers_PhoneNumber_size)]; char f104[(7 + spotify_login5_v3_credentials_OneTimeToken_size)]; char f105[(7 + spotify_login5_v3_credentials_ParentChildCredential_size)]; char f106[(7 + spotify_login5_v3_credentials_AppleSignInCredential_size)]; char f107[(7 + spotify_login5_v3_credentials_SamsungSignInCredential_size)]; char f108[(7 + spotify_login5_v3_credentials_GoogleSignInCredential_size)];};
#endif
/* spotify_login5_v3_Challenges_size depends on runtime parameters */
/* spotify_login5_v3_ChallengeSolutions_size depends on runtime parameters */
/* spotify_login5_v3_LoginRequest_size depends on runtime parameters */
/* spotify_login5_v3_LoginOk_size depends on runtime parameters */
/* spotify_login5_v3_LoginResponse_size depends on runtime parameters */
#if defined(spotify_login5_v3_challenges_HashcashChallenge_size) && defined(spotify_login5_v3_challenges_CodeChallenge_size)
#define spotify_login5_v3_Challenge_size         (0 + sizeof(union spotify_login5_v3_Challenge_challenge_size_union))
#endif
#if defined(spotify_login5_v3_challenges_HashcashSolution_size) && defined(spotify_login5_v3_challenges_CodeSolution_size)
#define spotify_login5_v3_ChallengeSolution_size (0 + sizeof(union spotify_login5_v3_ChallengeSolution_solution_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
