/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_USER_INFO_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_SPOTIFY_LOGIN5_V3_USER_INFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _spotify_login5_v3_UserInfo_Gender {
    spotify_login5_v3_UserInfo_Gender_UNKNOWN = 0,
    spotify_login5_v3_UserInfo_Gender_MALE = 1,
    spotify_login5_v3_UserInfo_Gender_FEMALE = 2,
    spotify_login5_v3_UserInfo_Gender_NEUTRAL = 3
} spotify_login5_v3_UserInfo_Gender;

/* Struct definitions */
typedef struct _spotify_login5_v3_UserInfo {
    pb_callback_t name;
    pb_callback_t email;
    bool email_verified;
    pb_callback_t birthdate;
    spotify_login5_v3_UserInfo_Gender gender;
    pb_callback_t phone_number;
    bool phone_number_verified;
    bool email_already_registered;
} spotify_login5_v3_UserInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _spotify_login5_v3_UserInfo_Gender_MIN spotify_login5_v3_UserInfo_Gender_UNKNOWN
#define _spotify_login5_v3_UserInfo_Gender_MAX spotify_login5_v3_UserInfo_Gender_NEUTRAL
#define _spotify_login5_v3_UserInfo_Gender_ARRAYSIZE ((spotify_login5_v3_UserInfo_Gender)(spotify_login5_v3_UserInfo_Gender_NEUTRAL+1))

#define spotify_login5_v3_UserInfo_gender_ENUMTYPE spotify_login5_v3_UserInfo_Gender


/* Initializer values for message structs */
#define spotify_login5_v3_UserInfo_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, _spotify_login5_v3_UserInfo_Gender_MIN, {{NULL}, NULL}, 0, 0}
#define spotify_login5_v3_UserInfo_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, _spotify_login5_v3_UserInfo_Gender_MIN, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_UserInfo_name_tag      1
#define spotify_login5_v3_UserInfo_email_tag     2
#define spotify_login5_v3_UserInfo_email_verified_tag 3
#define spotify_login5_v3_UserInfo_birthdate_tag 4
#define spotify_login5_v3_UserInfo_gender_tag    5
#define spotify_login5_v3_UserInfo_phone_number_tag 6
#define spotify_login5_v3_UserInfo_phone_number_verified_tag 7
#define spotify_login5_v3_UserInfo_email_already_registered_tag 8

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_UserInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   email,             2) \
X(a, STATIC,   SINGULAR, BOOL,     email_verified,    3) \
X(a, CALLBACK, SINGULAR, STRING,   birthdate,         4) \
X(a, STATIC,   SINGULAR, UENUM,    gender,            5) \
X(a, CALLBACK, SINGULAR, STRING,   phone_number,      6) \
X(a, STATIC,   SINGULAR, BOOL,     phone_number_verified,   7) \
X(a, STATIC,   SINGULAR, BOOL,     email_already_registered,   8)
#define spotify_login5_v3_UserInfo_CALLBACK pb_default_field_callback
#define spotify_login5_v3_UserInfo_DEFAULT NULL

extern const pb_msgdesc_t spotify_login5_v3_UserInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_UserInfo_fields &spotify_login5_v3_UserInfo_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_UserInfo_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
