/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "spotify/login5/v3/challenges/code.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(spotify_login5_v3_challenges_CodeChallenge, spotify_login5_v3_challenges_CodeChallenge, AUTO)


PB_BIND(spotify_login5_v3_challenges_CodeSolution, spotify_login5_v3_challenges_CodeSolution, AUTO)





