/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_CHALLENGES_SPOTIFY_LOGIN5_V3_CHALLENGES_CODE_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_CHALLENGES_SPOTIFY_LOGIN5_V3_CHALLENGES_CODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _spotify_login5_v3_challenges_CodeChallenge_Method {
    spotify_login5_v3_challenges_CodeChallenge_Method_UNKNOWN = 0,
    spotify_login5_v3_challenges_CodeChallenge_Method_SMS = 1
} spotify_login5_v3_challenges_CodeChallenge_Method;

/* Struct definitions */
typedef struct _spotify_login5_v3_challenges_CodeChallenge {
    spotify_login5_v3_challenges_CodeChallenge_Method method;
    int32_t code_length;
    int32_t expires_in;
    pb_callback_t canonical_phone_number;
} spotify_login5_v3_challenges_CodeChallenge;

typedef struct _spotify_login5_v3_challenges_CodeSolution {
    pb_callback_t code;
} spotify_login5_v3_challenges_CodeSolution;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _spotify_login5_v3_challenges_CodeChallenge_Method_MIN spotify_login5_v3_challenges_CodeChallenge_Method_UNKNOWN
#define _spotify_login5_v3_challenges_CodeChallenge_Method_MAX spotify_login5_v3_challenges_CodeChallenge_Method_SMS
#define _spotify_login5_v3_challenges_CodeChallenge_Method_ARRAYSIZE ((spotify_login5_v3_challenges_CodeChallenge_Method)(spotify_login5_v3_challenges_CodeChallenge_Method_SMS+1))

#define spotify_login5_v3_challenges_CodeChallenge_method_ENUMTYPE spotify_login5_v3_challenges_CodeChallenge_Method



/* Initializer values for message structs */
#define spotify_login5_v3_challenges_CodeChallenge_init_default {_spotify_login5_v3_challenges_CodeChallenge_Method_MIN, 0, 0, {{NULL}, NULL}}
#define spotify_login5_v3_challenges_CodeSolution_init_default {{{NULL}, NULL}}
#define spotify_login5_v3_challenges_CodeChallenge_init_zero {_spotify_login5_v3_challenges_CodeChallenge_Method_MIN, 0, 0, {{NULL}, NULL}}
#define spotify_login5_v3_challenges_CodeSolution_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_challenges_CodeChallenge_method_tag 1
#define spotify_login5_v3_challenges_CodeChallenge_code_length_tag 2
#define spotify_login5_v3_challenges_CodeChallenge_expires_in_tag 3
#define spotify_login5_v3_challenges_CodeChallenge_canonical_phone_number_tag 4
#define spotify_login5_v3_challenges_CodeSolution_code_tag 1

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_challenges_CodeChallenge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    method,            1) \
X(a, STATIC,   SINGULAR, INT32,    code_length,       2) \
X(a, STATIC,   SINGULAR, INT32,    expires_in,        3) \
X(a, CALLBACK, SINGULAR, STRING,   canonical_phone_number,   4)
#define spotify_login5_v3_challenges_CodeChallenge_CALLBACK pb_default_field_callback
#define spotify_login5_v3_challenges_CodeChallenge_DEFAULT NULL

#define spotify_login5_v3_challenges_CodeSolution_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   code,              1)
#define spotify_login5_v3_challenges_CodeSolution_CALLBACK pb_default_field_callback
#define spotify_login5_v3_challenges_CodeSolution_DEFAULT NULL

extern const pb_msgdesc_t spotify_login5_v3_challenges_CodeChallenge_msg;
extern const pb_msgdesc_t spotify_login5_v3_challenges_CodeSolution_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_challenges_CodeChallenge_fields &spotify_login5_v3_challenges_CodeChallenge_msg
#define spotify_login5_v3_challenges_CodeSolution_fields &spotify_login5_v3_challenges_CodeSolution_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_challenges_CodeChallenge_size depends on runtime parameters */
/* spotify_login5_v3_challenges_CodeSolution_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
