/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_CHALLENGES_SPOTIFY_LOGIN5_V3_CHALLENGES_HASHCASH_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_CHALLENGES_SPOTIFY_LOGIN5_V3_CHALLENGES_HASHCASH_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/duration.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _spotify_login5_v3_challenges_HashcashChallenge {
    pb_callback_t prefix;
    int32_t length;
} spotify_login5_v3_challenges_HashcashChallenge;

typedef struct _spotify_login5_v3_challenges_HashcashSolution {
    pb_callback_t suffix;
    bool has_duration;
    google_protobuf_Duration duration;
} spotify_login5_v3_challenges_HashcashSolution;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define spotify_login5_v3_challenges_HashcashChallenge_init_default {{{NULL}, NULL}, 0}
#define spotify_login5_v3_challenges_HashcashSolution_init_default {{{NULL}, NULL}, false, google_protobuf_Duration_init_default}
#define spotify_login5_v3_challenges_HashcashChallenge_init_zero {{{NULL}, NULL}, 0}
#define spotify_login5_v3_challenges_HashcashSolution_init_zero {{{NULL}, NULL}, false, google_protobuf_Duration_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_challenges_HashcashChallenge_prefix_tag 1
#define spotify_login5_v3_challenges_HashcashChallenge_length_tag 2
#define spotify_login5_v3_challenges_HashcashSolution_suffix_tag 1
#define spotify_login5_v3_challenges_HashcashSolution_duration_tag 2

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_challenges_HashcashChallenge_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    prefix,            1) \
X(a, STATIC,   SINGULAR, INT32,    length,            2)
#define spotify_login5_v3_challenges_HashcashChallenge_CALLBACK pb_default_field_callback
#define spotify_login5_v3_challenges_HashcashChallenge_DEFAULT NULL

#define spotify_login5_v3_challenges_HashcashSolution_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    suffix,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  duration,          2)
#define spotify_login5_v3_challenges_HashcashSolution_CALLBACK pb_default_field_callback
#define spotify_login5_v3_challenges_HashcashSolution_DEFAULT NULL
#define spotify_login5_v3_challenges_HashcashSolution_duration_MSGTYPE google_protobuf_Duration

extern const pb_msgdesc_t spotify_login5_v3_challenges_HashcashChallenge_msg;
extern const pb_msgdesc_t spotify_login5_v3_challenges_HashcashSolution_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_challenges_HashcashChallenge_fields &spotify_login5_v3_challenges_HashcashChallenge_msg
#define spotify_login5_v3_challenges_HashcashSolution_fields &spotify_login5_v3_challenges_HashcashSolution_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_challenges_HashcashChallenge_size depends on runtime parameters */
/* spotify_login5_v3_challenges_HashcashSolution_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
