/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "spotify/login5/v3/credentials/credentials.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(spotify_login5_v3_credentials_StoredCredential, spotify_login5_v3_credentials_StoredCredential, AUTO)


PB_BIND(spotify_login5_v3_credentials_Password, spotify_login5_v3_credentials_Password, AUTO)


PB_BIND(spotify_login5_v3_credentials_FacebookAccessToken, spotify_login5_v3_credentials_FacebookAccessToken, AUTO)


PB_BIND(spotify_login5_v3_credentials_OneTimeToken, spotify_login5_v3_credentials_OneTimeToken, AUTO)


PB_BIND(spotify_login5_v3_credentials_ParentChildCredential, spotify_login5_v3_credentials_ParentChildCredential, AUTO)


PB_BIND(spotify_login5_v3_credentials_AppleSignInCredential, spotify_login5_v3_credentials_AppleSignInCredential, AUTO)


PB_BIND(spotify_login5_v3_credentials_SamsungSignInCredential, spotify_login5_v3_credentials_SamsungSignInCredential, AUTO)


PB_BIND(spotify_login5_v3_credentials_GoogleSignInCredential, spotify_login5_v3_credentials_GoogleSignInCredential, AUTO)



