/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SPOTIFY_LOGIN5_V3_CREDENTIALS_SPOTIFY_LOGIN5_V3_CREDENTIALS_CREDENTIALS_PB_H_INCLUDED
#define PB_SPOTIFY_LOGIN5_V3_CREDENTIALS_SPOTIFY_LOGIN5_V3_CREDENTIALS_CREDENTIALS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _spotify_login5_v3_credentials_StoredCredential {
    pb_callback_t username;
    pb_callback_t data;
} spotify_login5_v3_credentials_StoredCredential;

typedef struct _spotify_login5_v3_credentials_Password {
    pb_callback_t id;
    pb_callback_t password;
    pb_callback_t padding;
} spotify_login5_v3_credentials_Password;

typedef struct _spotify_login5_v3_credentials_FacebookAccessToken {
    pb_callback_t fb_uid;
    pb_callback_t access_token;
} spotify_login5_v3_credentials_FacebookAccessToken;

typedef struct _spotify_login5_v3_credentials_OneTimeToken {
    pb_callback_t token;
} spotify_login5_v3_credentials_OneTimeToken;

typedef struct _spotify_login5_v3_credentials_ParentChildCredential {
    pb_callback_t child_id;
    bool has_parent_stored_credential;
    spotify_login5_v3_credentials_StoredCredential parent_stored_credential;
} spotify_login5_v3_credentials_ParentChildCredential;

typedef struct _spotify_login5_v3_credentials_AppleSignInCredential {
    pb_callback_t auth_code;
    pb_callback_t redirect_uri;
    pb_callback_t bundle_id;
} spotify_login5_v3_credentials_AppleSignInCredential;

typedef struct _spotify_login5_v3_credentials_SamsungSignInCredential {
    pb_callback_t auth_code;
    pb_callback_t redirect_uri;
    pb_callback_t id_token;
    pb_callback_t token_endpoint_url;
} spotify_login5_v3_credentials_SamsungSignInCredential;

typedef struct _spotify_login5_v3_credentials_GoogleSignInCredential {
    pb_callback_t auth_code;
    pb_callback_t redirect_uri;
} spotify_login5_v3_credentials_GoogleSignInCredential;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define spotify_login5_v3_credentials_StoredCredential_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_Password_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_FacebookAccessToken_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_OneTimeToken_init_default {{{NULL}, NULL}}
#define spotify_login5_v3_credentials_ParentChildCredential_init_default {{{NULL}, NULL}, false, spotify_login5_v3_credentials_StoredCredential_init_default}
#define spotify_login5_v3_credentials_AppleSignInCredential_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_SamsungSignInCredential_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_GoogleSignInCredential_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_StoredCredential_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_Password_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_FacebookAccessToken_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_OneTimeToken_init_zero {{{NULL}, NULL}}
#define spotify_login5_v3_credentials_ParentChildCredential_init_zero {{{NULL}, NULL}, false, spotify_login5_v3_credentials_StoredCredential_init_zero}
#define spotify_login5_v3_credentials_AppleSignInCredential_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_SamsungSignInCredential_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define spotify_login5_v3_credentials_GoogleSignInCredential_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define spotify_login5_v3_credentials_StoredCredential_username_tag 1
#define spotify_login5_v3_credentials_StoredCredential_data_tag 2
#define spotify_login5_v3_credentials_Password_id_tag 1
#define spotify_login5_v3_credentials_Password_password_tag 2
#define spotify_login5_v3_credentials_Password_padding_tag 3
#define spotify_login5_v3_credentials_FacebookAccessToken_fb_uid_tag 1
#define spotify_login5_v3_credentials_FacebookAccessToken_access_token_tag 2
#define spotify_login5_v3_credentials_OneTimeToken_token_tag 1
#define spotify_login5_v3_credentials_ParentChildCredential_child_id_tag 1
#define spotify_login5_v3_credentials_ParentChildCredential_parent_stored_credential_tag 2
#define spotify_login5_v3_credentials_AppleSignInCredential_auth_code_tag 1
#define spotify_login5_v3_credentials_AppleSignInCredential_redirect_uri_tag 2
#define spotify_login5_v3_credentials_AppleSignInCredential_bundle_id_tag 3
#define spotify_login5_v3_credentials_SamsungSignInCredential_auth_code_tag 1
#define spotify_login5_v3_credentials_SamsungSignInCredential_redirect_uri_tag 2
#define spotify_login5_v3_credentials_SamsungSignInCredential_id_token_tag 3
#define spotify_login5_v3_credentials_SamsungSignInCredential_token_endpoint_url_tag 4
#define spotify_login5_v3_credentials_GoogleSignInCredential_auth_code_tag 1
#define spotify_login5_v3_credentials_GoogleSignInCredential_redirect_uri_tag 2

/* Struct field encoding specification for nanopb */
#define spotify_login5_v3_credentials_StoredCredential_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   username,          1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define spotify_login5_v3_credentials_StoredCredential_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_StoredCredential_DEFAULT NULL

#define spotify_login5_v3_credentials_Password_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   password,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    padding,           3)
#define spotify_login5_v3_credentials_Password_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_Password_DEFAULT NULL

#define spotify_login5_v3_credentials_FacebookAccessToken_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   fb_uid,            1) \
X(a, CALLBACK, SINGULAR, STRING,   access_token,      2)
#define spotify_login5_v3_credentials_FacebookAccessToken_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_FacebookAccessToken_DEFAULT NULL

#define spotify_login5_v3_credentials_OneTimeToken_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   token,             1)
#define spotify_login5_v3_credentials_OneTimeToken_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_OneTimeToken_DEFAULT NULL

#define spotify_login5_v3_credentials_ParentChildCredential_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   child_id,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parent_stored_credential,   2)
#define spotify_login5_v3_credentials_ParentChildCredential_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_ParentChildCredential_DEFAULT NULL
#define spotify_login5_v3_credentials_ParentChildCredential_parent_stored_credential_MSGTYPE spotify_login5_v3_credentials_StoredCredential

#define spotify_login5_v3_credentials_AppleSignInCredential_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   auth_code,         1) \
X(a, CALLBACK, SINGULAR, STRING,   redirect_uri,      2) \
X(a, CALLBACK, SINGULAR, STRING,   bundle_id,         3)
#define spotify_login5_v3_credentials_AppleSignInCredential_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_AppleSignInCredential_DEFAULT NULL

#define spotify_login5_v3_credentials_SamsungSignInCredential_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   auth_code,         1) \
X(a, CALLBACK, SINGULAR, STRING,   redirect_uri,      2) \
X(a, CALLBACK, SINGULAR, STRING,   id_token,          3) \
X(a, CALLBACK, SINGULAR, STRING,   token_endpoint_url,   4)
#define spotify_login5_v3_credentials_SamsungSignInCredential_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_SamsungSignInCredential_DEFAULT NULL

#define spotify_login5_v3_credentials_GoogleSignInCredential_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   auth_code,         1) \
X(a, CALLBACK, SINGULAR, STRING,   redirect_uri,      2)
#define spotify_login5_v3_credentials_GoogleSignInCredential_CALLBACK pb_default_field_callback
#define spotify_login5_v3_credentials_GoogleSignInCredential_DEFAULT NULL

extern const pb_msgdesc_t spotify_login5_v3_credentials_StoredCredential_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_Password_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_FacebookAccessToken_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_OneTimeToken_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_ParentChildCredential_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_AppleSignInCredential_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_SamsungSignInCredential_msg;
extern const pb_msgdesc_t spotify_login5_v3_credentials_GoogleSignInCredential_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define spotify_login5_v3_credentials_StoredCredential_fields &spotify_login5_v3_credentials_StoredCredential_msg
#define spotify_login5_v3_credentials_Password_fields &spotify_login5_v3_credentials_Password_msg
#define spotify_login5_v3_credentials_FacebookAccessToken_fields &spotify_login5_v3_credentials_FacebookAccessToken_msg
#define spotify_login5_v3_credentials_OneTimeToken_fields &spotify_login5_v3_credentials_OneTimeToken_msg
#define spotify_login5_v3_credentials_ParentChildCredential_fields &spotify_login5_v3_credentials_ParentChildCredential_msg
#define spotify_login5_v3_credentials_AppleSignInCredential_fields &spotify_login5_v3_credentials_AppleSignInCredential_msg
#define spotify_login5_v3_credentials_SamsungSignInCredential_fields &spotify_login5_v3_credentials_SamsungSignInCredential_msg
#define spotify_login5_v3_credentials_GoogleSignInCredential_fields &spotify_login5_v3_credentials_GoogleSignInCredential_msg

/* Maximum encoded size of messages (where known) */
/* spotify_login5_v3_credentials_StoredCredential_size depends on runtime parameters */
/* spotify_login5_v3_credentials_Password_size depends on runtime parameters */
/* spotify_login5_v3_credentials_FacebookAccessToken_size depends on runtime parameters */
/* spotify_login5_v3_credentials_OneTimeToken_size depends on runtime parameters */
/* spotify_login5_v3_credentials_ParentChildCredential_size depends on runtime parameters */
/* spotify_login5_v3_credentials_AppleSignInCredential_size depends on runtime parameters */
/* spotify_login5_v3_credentials_SamsungSignInCredential_size depends on runtime parameters */
/* spotify_login5_v3_credentials_GoogleSignInCredential_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
